### PR TITLE
Feature: auto reward EP when boss wipe. Default disabled.

### PR DESCRIPTION
**Pull request by jpxthu**

### CODE REVIEW

**Comment by jpxthu** [comment]
@marknl please review this PR if you are happy to do this.

Wipe auto reward was added. Re-organized the logics.

**Comment by marknl** [comment]
@jpxthu I'll test this tonight when we run BWL. WIll report my findings here.

**Comment by marknl** [comment]
@jpxthu I ran BWL last night with this code. Worked fine.
This pops up every time you enter or leave an instance btw. Guess that's because of the GROUP_ROSTER_UPDATE.

Everything worked fine. We didn't wipe, so didn't test that.

**Comment by jpxthu** [comment]
@marknl Thanks for your feedback. The popup frame will show every time you:
1. Become RL or ML, and have offier authority
2. Been RL or ML, and get officer authority
3. Been RL or ML, have officer authority, then reload or enter game.

Triggered both GROUP_ROSTER_UPDATE and GUILD_ROSTER_UPDATE. Code in here:
https://github.com/jpxthu/EPGP-Classic/pull/42/files#diff-93d65e5693b0c49331c4dd8425093334R453-R455
https://github.com/jpxthu/EPGP-Classic/pull/42/files#diff-93d65e5693b0c49331c4dd8425093334R53-R69

**Comment by marknl** [comment]
yeah I figured. It think it's fine how it works now. Thanks for adding my work and thanks for re-organizing the code. This was my first wow-addon PR :)

**Pull request merged**
